"""tables update

Revision ID: 10676019f315
Revises: 913a2c58f393
Create Date: 2023-08-06 08:53:36.508565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10676019f315'
down_revision = '913a2c58f393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('programmers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty', sa.String(), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('strength')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('state')

    with op.batch_alter_table('programmers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strength', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('specialty')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
