"""empty message

Revision ID: e3e0038cd548
Revises: a89e5087e698
Create Date: 2023-08-06 14:24:43.181214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e0038cd548'
down_revision = 'a89e5087e698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programmers', schema=None) as batch_op:
        batch_op.alter_column('specialty',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programmers', schema=None) as batch_op:
        batch_op.alter_column('specialty',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
